### PR TITLE
WIP Crossdock coverage over headers support

### PR DESCRIPTION
**Pull request by kriskowal**

### CODE REVIEW

**Comment by breerly** [comment]
Looks like you're trying to merge into `crossdock-echo-behaviors` - that's wrong isn't it?

**Comment by kriskowal** [comment]
@breerly temporarily to keep the diff clean.

**Comment by breerly** [comment]
Why not off of `master`?

**Comment by abhinav** [comment]
Presumably, these changes depend on the changes in crossdock-echo-behaviors. If it's off of master, then the diff will include the changes from crossdock-echo-behaviors which has already been reviewed.

**Comment by kriskowal** [comment]
@breerly crossdock-echo-behaviors contains a refactor that makes the crossdock behaviors run locally and more easily extended. This could not be rebased on master without significant makework. I expect we’ll land crossdock-echo-behaviors before we get cross-language coverage on this branch, at which point I’ll rebase on master and retarget the PR.

**Comment by breerly** [comment]
Got it - makes sense!

**Comment by abhinav** [comment]
Closing in favor of https://github.com/yarpc/yarpc-node/pull/70

**Pull request closed without merging**
