### PR TITLE
Echo tests

### PR DESCRIPTION
**Pull request by kriskowal**
This is the portion of #45 that can land in advance of the crossdock validation across languages so I can build on the refactored behaviors.

### CODE REVIEW

**Comment by kriskowal** [comment]
r @yarpc/yarpc

**Comment by junchaowu** [comment]
Can you give us more description on what you have done in this PR like which error you are testing? It will be very useful for us to review it.

**Comment by kriskowal** [comment]
@junchaowu This does not do error testing. This includes all of the changes in the crossdock-echo-behaviors branch, including unit tests for those behaviors, but does not add the crossdock integration. This allows me to land the changes and build headers and error branches on that work without blocking on Python crossdock-echo-behaviors is ready to land.

**Comment by abhinav** [comment]
This looks like the changes from the other branch that have already been reviewed. LGTM.

**Pull request merged**
