### PR TITLE
TChannel headers support in all encodings

### PR DESCRIPTION
**Pull request by kriskowal**

### CODE REVIEW

**Comment by breerly** [comment]
Wondering if we should keep headers in a branch so that we can ship with a Crossdock test for all langs...

What do you think?

**Comment by kriskowal** [comment]
I think we can land this ASAP to unblock, and revisit a branch for the crossdock coverage.

**Comment by breerly** [comment]
I could buy this - although it could mean revisiting if we don't get it right the first time.

**Comment by kriskowal** [comment]
I expect we’ll all need to circle back more than once. This doesn’t do the header splitting between context.headers and request.headers, much less filter YARPC significant headers, or any of those other concerns.

**Comment by abhinav** [comment]
:

**Comment by breerly** [comment]
:shipit:

**Pull request merged**
